set -ex
# python train.py --name recap2raw_res_ls --mode pix2pix --direction BtoA --dataset_mode unaligned --norm instance --pool_size 0 --gpu_ids 0 --serial_batches --batch_size 48 --preprocess exp --no_flip --n_epochs 15 --n_epochs_decay 15 --freq_weight 0 --lambda_L1 100 --netG resnet_9blocks --gan_mode lsgan
# python train.py --name attack1 --mode pix2pix --direction AtoB --dataset_mode unaligned --norm instance --pool_size 0 --gpu_ids 0 --serial_batches --batch_size 26 --preprocess exp --no_flip --n_epochs 20 --n_epochs_decay 20 --freq_weight 3 --lambda_L1 100 --netG resnet_9blocks --simulator --simulator_epoch 30
# python train.py --name attack2 --mode pix2pix --direction AtoB --dataset_mode unaligned --norm instance --pool_size 0 --gpu_ids 0 --serial_batches --batch_size 26 --preprocess exp --no_flip --n_epochs 20 --n_epochs_decay 20 --freq_weight 3 --lambda_L1 100 --netG resnet_9blocks --simulator --simulator_epoch 30 --netD n_layers --n_layers_D 2

# python train.py --name raw2recap0 --mode pix2pix --direction AtoB --dataset_mode unaligned --norm instance --pool_size 0 --gpu_ids 0 --serial_batches --batch_size 128 --preprocess exp --no_flip --n_epochs 30 --n_epochs_decay 30 --lambda_L1 100
# python train.py --name recap2raw0 --mode pix2pix --direction BtoA --dataset_mode unaligned --norm instance --pool_size 0 --gpu_ids 0 --serial_batches --batch_size 128 --preprocess exp --no_flip --n_epochs 40 --n_epochs_decay 40 --lambda_L1 100
# python train.py --name attack_bas --mode pix2pix --direction AtoB --dataset_mode unaligned --norm instance --pool_size 0 --gpu_ids 0 --serial_batches --batch_size 128 --preprocess exp --no_flip --n_epochs 40 --n_epochs_decay 40 --lambda_L1 300 --simulator --netD n_layers --n_layers_D 2
# python train.py --name attack_pre --mode pix2pix --direction AtoB --dataset_mode unaligned --norm instance --pool_size 0 --gpu_ids 0 --serial_batches --batch_size 128 --preprocess exp --no_flip --n_epochs 15 --n_epochs_decay 15 --lambda_L1 300 --simulator --netD n_layers --n_layers_D 2 --pretrained_generator
# python train.py --name attack_frq --mode pix2pix --direction AtoB --dataset_mode unaligned --norm instance --pool_size 0 --gpu_ids 0 --serial_batches --batch_size 128 --preprocess exp --no_flip --n_epochs 15 --n_epochs_decay 15 --lambda_L1 300 --simulator --netD n_layers --n_layers_D 2 --pretrained_generator --freq_weight 3

# python train.py --name iphoneD_raw2recap_freq1_u256 --mode pix2pix --direction AtoB --dataset_mode unaligned --norm instance --pool_size 0 --gpu_ids 0 --serial_batches --batch_size 16 --preprocess exp --no_flip --n_epochs 10 --n_epochs_decay 5 --lambda_L1 100 --freq_weight 1 --crop_size 1024 --netG unet_256
python train.py --name iphoneD_attack_freq1_uu --mode pix2pix --direction AtoB --dataset_mode unaligned --norm instance --pool_size 0 --gpu_ids 0 --serial_batches --batch_size 4 --preprocess exp --no_flip --n_epochs 10 --n_epochs_decay 5 --lambda_L1 100 --netG uformer_unet --simulator --netD n_layers --n_layers_D 2 --simulator_epoch 10 --freq_weight 1 --crop_size 1024 --lr 0.00005
